baseURL = '/'
languageCode = 'en-us'
title = "Yalchin's Blog"
buildDrafts = false
paginate = 5
theme = "hugo-theme-hello-friend-ng"
disqusShortname = 'blog-yalchin-ml'


[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'paraiso-dark'
    tabWidth = 4


[languages]
    [languages.en]
    languageName = "English"
    title = "Yalchin's Blog"
    subtitle = "Notes about the things I learn"
    keywords = "Yalchin Mammadli Software Developer Python Golang Node.js"
    copyright = "Yalchin Mammadli"
    menuMore = "Show more"
    readMore = "Read more"
    newerPosts = "New"
    olderPosts = "Previous"

    [languages.en.params.logo]
      logoText = "Hello, Friend"
      logoHomeLink = "/"


[[menu.main]]
    identifier = "blog"
    name       = "Blog"
    url        = "/posts"

[[menu.main]]
    identifier = "resume"
    name       = "Resume"
    url        = "/resume/cv.pdf"

[[menu.main]]
    identifier = "contact"
    name       = "Contact"
    url        = "/personal/contact"